In [20]:
import sys
sys.executable

'/home/wangwei/miniconda3/envs/pytorch/bin/python'

In [2]:
import torch

In [6]:
# 构造5*3的矩阵，不初始化
x = torch.empty(5, 3)
print(x)

tensor([[ 1.0581e+30,  4.5734e-41, -6.2408e-32],
        [ 3.0834e-41,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [-6.2846e-32,  3.0834e-41, -2.1776e-32]])


In [7]:
# 构造5*3的矩阵，随机初始化
x = torch.rand(5, 3)
print(x)

tensor([[0.7534, 0.7250, 0.0791],
        [0.5055, 0.1938, 0.9893],
        [0.4639, 0.8061, 0.9436],
        [0.1779, 0.3917, 0.7097],
        [0.6815, 0.9625, 0.8980]])


In [8]:
# 构造一个矩阵全为 0，而且数据类型是 long.

x = torch.zeros(5, 3, dtype=torch.long)
print(x)


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [14]:
# 构造一个张量
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [16]:
# 使用已有的tensor创建tensor
a = x.new_ones(5, 3, dtype=torch.double)
print(x)
print(a)

print('----')
b = torch.randn_like(a, dtype=torch.float)
print(b) # 只是含有同样的size

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
----
tensor([[ 1.7586,  0.0839, -0.2988],
        [ 0.4176, -1.6826, -0.1452],
        [-1.0935,  1.2077, -2.1389],
        [ 1.1880, -1.2563,  0.6672],
        [ 0.1400,  1.7900,  0.1060]])


In [19]:
# 获取维度
print(b.size())

torch.Size([5, 3])


In [28]:
x = b
y = torch.rand(5, 3)
x+y

tensor([[ 2.4226,  0.1002,  0.2294],
        [ 1.3576, -1.1726,  0.6958],
        [-0.9049,  1.5331, -1.6621],
        [ 1.8670, -1.0410,  0.9820],
        [ 0.7725,  2.1376,  0.7860]])

In [29]:
torch.add(x, y)

tensor([[ 2.4226,  0.1002,  0.2294],
        [ 1.3576, -1.1726,  0.6958],
        [-0.9049,  1.5331, -1.6621],
        [ 1.8670, -1.0410,  0.9820],
        [ 0.7725,  2.1376,  0.7860]])

In [30]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
result

tensor([[ 2.4226,  0.1002,  0.2294],
        [ 1.3576, -1.1726,  0.6958],
        [-0.9049,  1.5331, -1.6621],
        [ 1.8670, -1.0410,  0.9820],
        [ 0.7725,  2.1376,  0.7860]])

In [31]:
y.add_(x)
y

tensor([[ 2.4226,  0.1002,  0.2294],
        [ 1.3576, -1.1726,  0.6958],
        [-0.9049,  1.5331, -1.6621],
        [ 1.8670, -1.0410,  0.9820],
        [ 0.7725,  2.1376,  0.7860]])

In [35]:
print(x)
# 类似Numpy的索引操作
print(x[:, 1])

tensor([[ 1.7586,  0.0839, -0.2988],
        [ 0.4176, -1.6826, -0.1452],
        [-1.0935,  1.2077, -2.1389],
        [ 1.1880, -1.2563,  0.6672],
        [ 0.1400,  1.7900,  0.1060]])
tensor([ 0.0839, -1.6826,  1.2077, -1.2563,  1.7900])


In [37]:
x = torch.randn(4, 4)
# view是把tensor按行优先的方式调整形状
y = x.view(16) # 16行
z = x.view(-1, 8) # 8列。-1表上的行会自动算
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [38]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3323])
-0.3322658836841583
