In [1]:
import torch

In [21]:
# 创建一个张量，设置 requires_grad=True 来跟踪与它相关的计算
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [22]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [23]:
y.grad_fn

In [9]:
print(y.grad_fn)

In [24]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [11]:
out

tensor(27., grad_fn=<MeanBackward0>)

In [25]:
# 只能调用一次
out.backward()

In [26]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [30]:
x = torch.randn(3, requires_grad=True)

In [31]:
y = x* 2

In [32]:
while y.data.norm() < 1000:
    y = y*2
    
print(y)

tensor([-315.9849, -775.9990,  916.3296], grad_fn=<MulBackward0>)


In [33]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [34]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
