In [5]:
import pandas as pd
import numpy as np

In [8]:
s1 = pd.Series([4,7,-5,3])
print(s1)

0    4
1    7
2   -5
3    3
dtype: int64


In [12]:
s1.values

array([ 4,  7, -5,  3])

In [14]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [16]:
s2 = pd.Series([4,7,-5,3], index=['a','b','c','d'])

In [17]:
print(s2)

a    4
b    7
c   -5
d    3
dtype: int64


In [18]:
s2['a']

4

In [21]:
s2[['a','c','b']]

a    4
c   -5
b    7
dtype: int64

In [22]:
'd' in s2

True

In [23]:
'e' in s2

False

In [32]:
# Series可以看成是定长的有序字典
dict = {'apple':1, 'pen':2, 'applepen':12}
s3 = pd.Series(dict)
#print(s3)
s3

apple        1
applepen    12
pen          2
dtype: int64

In [66]:
#DataFrame
data = {
    'year':[2012,2013,2014,2015],
    'icome':[100,200,300,50],
    'pay':[50,60,70,25]
}
df1 = pd.DataFrame(data)
df1
#print(df1)

icome  pay  year
0    100   50  2012
1    200   60  2013
2    300   70  2014
3     50   25  2015

In [68]:
df1.sort_values(by='pay') # 对某一列排序，其他列受影响

icome  pay  year
3     50   25  2015
0    100   50  2012
1    200   60  2013
2    300   70  2014

In [69]:
df1 # 原df不变

icome  pay  year
0    100   50  2012
1    200   60  2013
2    300   70  2014
3     50   25  2015

In [39]:
# TODO np
df2 = pd.DataFrame(np.arange(12).reshape((3,4)))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [47]:
df3 = pd.DataFrame(np.arange(12).reshape((3,4)), index=['a','b','c'], columns=['甲','乙','丙','丁'])
df3

甲  乙   丙   丁
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [49]:
df3.index

Index([u'a', u'b', u'c'], dtype='object')

In [50]:
df3.columns

Index([u'甲', u'乙', u'丙', u'丁'], dtype='object')

In [51]:
df3.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
df3.describe()

甲    乙     丙     丁
count  3.0  3.0   3.0   3.0
mean   4.0  5.0   6.0   7.0
std    4.0  4.0   4.0   4.0
min    0.0  1.0   2.0   3.0
25%    2.0  3.0   4.0   5.0
50%    4.0  5.0   6.0   7.0
75%    6.0  7.0   8.0   9.0
max    8.0  9.0  10.0  11.0

In [55]:
df3.T # 转置

a  b   c
甲  0  4   8
乙  1  5   9
丙  2  6  10
丁  3  7  11

In [57]:
df3

甲  乙   丙   丁
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [59]:
df3.sort_index(axis=1) #列排序

丁   丙  乙  甲
a   3   2  1  0
b   7   6  5  4
c  11  10  9  8

In [62]:
df3.sort_index(axis=0) #行排序

甲  乙   丙   丁
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [64]:
df3.sort_values(by='丙') # 对某一列排序（其它列也受影响保持对齐）

甲  乙   丙   丁
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11

In [45]:
np.arange(12).reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
[1,2,3]

[1, 2, 3]